// JT/T 808 (2013 header) framing and basic GPS location messages.
export function checksum(bytes){return bytes.reduce((n,b)=>n^b,0)}
export function bcd(bytes){return [...bytes].map(b=>b.toString(16).padStart(2,'0')).join('')}
export function unescape(bytes){let out=[];for(let i=0;i<bytes.length;i++){if(bytes[i]===0x7d){if(++i>=bytes.length)throw Error('truncated escape');if(bytes[i]===1)out.push(0x7d);else if(bytes[i]===2)out.push(0x7e);else throw Error('bad escape')}else out.push(bytes[i])}return Buffer.from(out)}
export function escape(bytes){const out=[];for(const b of bytes){if(b===0x7e)out.push(0x7d,2);else if(b===0x7d)out.push(0x7d,1);else out.push(b)}return Buffer.from(out)}
export function parse(frame){if(frame[0]!==0x7e||frame.at(-1)!==0x7e)throw Error('bad boundaries');const p=unescape(frame.subarray(1,-1));if(p.length<13||checksum(p)!==0)throw Error('length/checksum');const id=p.readUInt16BE(0),attr=p.readUInt16BE(2),len=attr&0x3ff,versioned=!!(attr&0x4000),subpacket=!!(attr&0x2000);const head=versioned?17:12;const offset=head+(subpacket?4:0);if(p.length!==offset+len+1)throw Error('body length');const terminal=versioned?bcd(p.subarray(5,15)):bcd(p.subarray(4,10));const seq=p.readUInt16BE(versioned?15:10);return{id,terminal,seq,versioned,body:p.subarray(offset,-1),fragmented:subpacket}}
export function encode(id,terminal,seq,body=Buffer.alloc(0),versioned=false){if(body.length>1023)throw Error('body too long');if(!/^(\d{12}|\d{20})$/.test(terminal)||versioned&&terminal.length!==20||!versioned&&terminal.length!==12)throw Error('invalid BCD terminal ID');const header=Buffer.alloc(versioned?17:12);header.writeUInt16BE(id,0);header.writeUInt16BE(body.length|(versioned?0x4000:0),2);if(versioned){header[4]=1;Buffer.from(terminal,'hex').copy(header,5);header.writeUInt16BE(seq&65535,15)}else{Buffer.from(terminal,'hex').copy(header,4);header.writeUInt16BE(seq&65535,10)}const raw=Buffer.concat([header,body]);return Buffer.concat([Buffer.from([0x7e]),escape(Buffer.concat([raw,Buffer.from([checksum(raw)])])),Buffer.from([0x7e])])}
export function ack(message,result=0,serial=0){const body=Buffer.alloc(5);body.writeUInt16BE(message.seq,0);body.writeUInt16BE(message.id,2);body[4]=result;return encode(0x8001,message.terminal,serial,body,message.versioned)}
export function location(message){const b=message.body;if(message.id!==0x0200||b.length<28)throw Error('not a complete location');const alarm=b.readUInt32BE(0),status=b.readUInt32BE(4);let lat=b.readUInt32BE(8)/1e6,lng=b.readUInt32BE(12)/1e6;if(status&4)lat=-lat;if(status&8)lng=-lng;if(Math.abs(lat)>90||Math.abs(lng)>180)throw Error('invalid coordinates');const time=bcd(b.subarray(22,28));const timestamp=`20${time.slice(0,2)}-${time.slice(2,4)}-${time.slice(4,6)}T${time.slice(6,8)}:${time.slice(8,10)}:${time.slice(10,12)}+08:00`;return{id:message.terminal,lat,lng,speed:b.readUInt16BE(18)/10,altitude:b.readUInt16BE(16),direction:b.readUInt16BE(20),timestamp:Number.isNaN(Date.parse(timestamp))?new Date().toISOString():new Date(timestamp).toISOString(),ignition:!!(status&1),gpsValid:!!(status&2),alarm,receivedAt:new Date().toISOString()}}
